scales:
  PID: 0x8009
  VID: 0x0922
slack:
  LOW_CHANNEL: '# hardware-bluey'
  VERY_LOW_CHANNEL: '# general'
  LOW_MESSAGE: ':bangbang: Liquid Nitrogen Trap at %s%% please refill soon. :bangbang:'
  VERY_LOW_MESSAGE: ':bangbang::bangbang: Liquid Nitrogen Trap at %s%% please refill Immediatly.:bangbang::bangbang:'
  PLOTTING: true
  START_AFTER_HOURS: 20 
  STOP_AFTER_HOURS: 8
logging:
  PATH: './Logs/'
  LOGNAME: '_Dewer_log'
  REMOVE_OLD: false
  ALERT_CRASH: false
weight:
  MAX_WEIGHT: 28.3
  DRY_WEIGHT: 11.0
  LOW: 0.25
  VERY_LOW: 0.1
